name: Depcheck

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check for unused dependencies (depcheck)
        run: |
          set -euo pipefail
          npx depcheck --ignores="@reduxjs/toolkit,@testing-library/user-event,@lhci/cli,@vitest/coverage-v8,autoprefixer,postcss,tailwindcss,wait-on" > depcheck-output.txt
          if grep -q 'Unused dependencies' depcheck-output.txt || grep -q 'Unused devDependencies' depcheck-output.txt; then
            echo 'Unused dependencies found:'
            cat depcheck-output.txt
            exit 1
          fi
