name: Depcheck

on:
  pull_request:
    branches:
      - '**'

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Check for unused dependencies (depcheck)
        run: |
          npx depcheck > depcheck-output.txt || true
          if grep -q 'Unused dependencies' depcheck-output.txt || grep -q 'Unused devDependencies' depcheck-output.txt; then
            echo 'Unused dependencies found:'
            cat depcheck-output.txt
            exit 1
          fi 
