name: Unimported Check

on:
  pull_request:
    branches:
      - '**'

jobs:
  unimported:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check for unused files (unimported)
        run: npx unimported --fail-on-unused
